Update flake.nix
This is what I changed in order to fix the broken ``ps-tools.for-0_15.purescript-language-server``.
It resolves this error:
```
error: undefined variable 'ps-tools'

       at /nix/store/m6kvn9wd3aa554z1qrq6qfmm4vjx3y43-source/tut01/flake.nix:70:21:

           69|                     # optional devShell tools
           70|                     ps-tools.for-0_15.purescript-language-server
             |                     ^
           71|                     # purescript-language-server
```